version: "3.9"

services:

  db:
    image: postgres:17-alpine
    container_name: inventory-db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: inventory-backend

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env

    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend

    container_name: inventory-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend


volumes:
  postgres_data: